version: "3.3"

services:

  proxy:
    image: "nginx:1.21"
    container_name: "proxy"
    network_mode: "host"
    restart: "unless-stopped"
    volumes:
      - "/etc/letsencrypt/:/etc/letsencrypt/"
      - "./configs/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf"
      - "/root/matrix/media:/media_files"

  postgresql-synapse:
    image: "postgres:13.0"
    container_name: "postgresql-synapse"
    network_mode: "host"
    restart: "unless-stopped"
    env_file:
      - "./configs/env/matrix.env"
#    environment:
#      POSTGRES_PASSWORD: "${SYNAPSE_POSTGRES_PASSWORD}"
#      POSTGRES_USER: "${SYNAPSE_POSTGRES_USER}"
#      POSTGRES_DB: "${SYNAPSE_POSTGRES_DB}"
#      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
    volumes:
      - "/opt/postgresql-synapse:/var/lib/postgresql/data"
      - "./configs/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh"

  synapse:
    image: "matrixdotorg/synapse:v1.44.0"
    container_name: "synapse"
    network_mode: "host"
    restart: "unless-stopped"
    env_file:
      - "./configs/env/matrix.env"
#    environment:
#      VIRTUAL_HOST: "${MATRIX_DOMAIN}"
#      VIRTUAL_PORT: "8008"
#      LETSENCRYPT_HOST: "${MATRIX_DOMAIN}"
#      SYNAPSE_SERVER_NAME: "${MATRIX_DOMAIN}"
#      SYNAPSE_REPORT_STATS: "yes"
    volumes:
      - "./data/synapse:/data"
    depends_on: [ "postgresql-synapse", "proxy" ]

  sygnal:
    image: "matrixdotorg/sygnal:v0.9.3"
    container_name: "sygnal"
    network_mode: "host"
    restart: "unless-stopped"
    environment:
      SYGNAL_CONF: "/sygnal.yaml"
    volumes:
      - "./configs/sygnal/sygnal.yaml:/sygnal.yaml"
    depends_on: [ "synapse", "proxy" ]

  postgresql-coturn:
    image: "postgres:13.0"
    container_name: "postgresql-coturn"
#    network_mode: "host"
    restart: "unless-stopped"
    ports:
      - "15432:5432"
    env_file:
      - "./configs/env/coturn.env"
#    environment:
#      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
#      POSTGRES_USER: "${POSTGRES_USER}"
#      POSTGRES_DB: "${POSTGRES_DB}"
#      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
    volumes:
      - "/opt/postgresql-coturn:/var/lib/postgresql/data"
      - "./configs/coturn/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh"

  coturn:
    image: "helllynx/coturn:4.5.1.3"
    container_name: "coturn"
    network_mode: "host"
    restart: "unless-stopped"
    volumes:
      - "./configs/coturn/turnserver.conf:/usr/local/etc/turnserver.conf"
    env_file:
      - "./configs/env/coturn.env"
#    environment:
#      INSTALL_PREFIX: "${INSTALL_PREFIX}"
#      TURNSERVER_GROUP: "${TURNSERVER_GROUP}"
#      TURNSERVER_USER: "${TURNSERVER_USER}"
    depends_on: [ "synapse", "proxy", "postgresql-coturn" ]
