version: "3.3"

services:

  proxy:
    image: "nginx:1.19"
    container_name: "proxy"
    network_mode: "host"
    restart: "always"
    volumes:
      - "./configs/nginx/certs/:/etc/nginx/certs/"
      - "./configs/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf"

  postgresql:
    image: "postgres:13.0"
    container_name: "postgresql"
    restart: "always"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
    volumes:
      - "./data/postgresdata:/var/lib/postgresql/data"
      - "./configs/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh"
    network_mode: "host"

  synapse:
    image: "matrixdotorg/synapse:v1.43.0"
    container_name: "synapse"
    volumes:
      - "./data/synapse:/data"
    environment:
      VIRTUAL_HOST: "${MATRIX_DOMAIN}"
      VIRTUAL_PORT: 8008
      LETSENCRYPT_HOST: "${MATRIX_DOMAIN}"
      SYNAPSE_SERVER_NAME: "${MATRIX_DOMAIN}"
      SYNAPSE_REPORT_STATS: "yes"
    depends_on: [ "postgresql", "proxy" ]
    network_mode: "host"

  sygnal:
    image: "matrixdotorg/sygnal:v0.9.3"
    container_name: "sygnal"
    network_mode: "host"
    restart: "always"
    environment:
      SYGNAL_CONF: "/sygnal.yaml"
    volumes:
      - "./configs/sygnal/sygnal.yaml:/sygnal.yaml"

  coturn:
    image: "helllynx/coturn:4.5.1.3"
    container_name: "coturn"
    volumes:
      - "./configs/coturn/turnserver.conf:/${INSTALL_PREFIX}/etc/turnserver.conf"
    environment:
      INSTALL_PREFIX: "${INSTALL_PREFIX}"
      TURNSERVER_GROUP: "${TURNSERVER_GROUP}"
      TURNSERVER_USER: "${TURNSERVER_USER}"
    depends_on: [ "synapse" ]
    network_mode: "host"

