version: "3.3"

services:

  proxy:
    image: "nginx:1.19"
    container_name: "proxy"
    network_mode: "host"
    restart: "always"
    volumes:
      - "./configs/nginx/certs/:/etc/nginx/certs/"
      - "./configs/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf"

  postgresqldb:
    image: "postgres:13.0"
    container_name: "postgresqldb"
    restart: "always"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
    volumes:
      - "./data/postgresdata:/var/lib/postgresqldb/data"
      - "./configs/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh"
    network_mode: "host"

  synapse:
    image: "matrixdotorg/synapse:v1.25.0"
    container_name: "synapse"
    volumes:
      - "./data/synapse:/data"
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      VIRTUAL_PORT: 8008
      LETSENCRYPT_HOST: "${LETSENCRYPT_HOST}"
      SYNAPSE_SERVER_NAME: "${SYNAPSE_SERVER_NAME}"
      SYNAPSE_REPORT_STATS: "yes"
#    ports:
#      - "8008:8008" # remove this on prod
    depends_on: [ "postgresqldb", "proxy" ]
    network_mode: "host"

  coturn:
    image: "helllynx/coturn:4.5.1.3"
    container_name: "coturn"
    volumes:
      - "./configs/coturn/turnserver.conf:/${INSTALL_PREFIX}/etc/turnserver.conf"
      - "./data/certs/matrix.zybc.pro/key.pem:/${INSTALL_PREFIX}/etc/ssl/private/privkey.pem"
      - "./data/certs/matrix.zybc.pro/cert.pem:/${INSTALL_PREFIX}/etc/ssl/certs/cert.pem"
    environment:
      INSTALL_PREFIX: "${INSTALL_PREFIX}"
      TURNSERVER_GROUP: "${TURNSERVER_GROUP}"
      TURNSERVER_USER: "${TURNSERVER_USER}"
#    ports:
#      ## STUN/TURN
#      - "3478:3478"
#      - "3478:3478/udp"
#      - "3479:3479"
#      - "3479:3479/udp"
#      # - "80:80"
#      # - "80:80/udp"
#      ## STUN/TURN SSL
#      - "5349:5349"
#      - "5349:5349/udp"
#      - "5350:5350"
#      - "5350:5350/udp"
#      # - "443:443"
#      # - "443:443/udp"
#      # Relay Ports
#      - "49152-65535:49152-65535"
#      - "49152-65535:49152-65535/udp"
    depends_on: [ "synapse" ]
    network_mode: "host"

  # mail:
  #     image: "juanluisbaptiste/postfix:alpine"
  #     container_name: "mail"
  #     environment:
  #         SMTP_SERVER: "${MAIL_DOMAIN}"
  #         SERVER_HOSTNAME: "${MAIL_DOMAIN}"
  #         SMTP_PORT: 587
  #     ports:
  #         - "1587:587"
  #     depends_on: ["synapse"]
  #     network_mode: "host"

volumes:
  postgresdata:
  certs:
  vhost:
  html:
